blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^home/',
        views.home,
        name='home'),
    url(r'^draft/',
        views.draft,
        name='draft'),
   	url(r'^user/(?P<username>\w+)/$',
        views.user,
        name='user'),
   	url(r'^tag/(?P<tag>\w+)/$',
        views.tag,
        name='tag'),
    url(r'^alluser/', views.alluser, name='alluser'),
    url(r'^alltag/', views.alltag, name='alltag'),
    url(r'^write/', views.write, name='write'),
    url(r'^search/', views.search, name='search'),
    url(r'^upload/', views.upload, name='upload'),
    url(r'^comment/', views.comment, name='comment'),
    url(r'^show/(?P<id>\d+)/$', views.show, name='show'),
]

mysite/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='blog:home', permanent=True),name='home'),
    url(r'^blog/', include('blog.urls')),
	url(r'^registration/', include('registration.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    
]

blog/models.py
from __future__ import unicode_literals

from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Tag(models.Model):
	tag = models.CharField(max_length=50)
	create_time = models.DateTimeField(auto_now_add=True,null=True, blank=True)

	class Meta:
		ordering = ['-create_time']

	def __str__(self):
		return self.tag	

	def get_articles(self):
		return Article.objects.filter(tags=self)

class Article(models.Model):
	PUBLISHED = 'P'
	DRAFT = 'D'
	STATUS = (
		(DRAFT,'Draft'),
		(PUBLISHED,'Published')
	)
	title = models.CharField(max_length=255)
	content = models.TextField(max_length=4000)
	markdown = models.TextField(max_length=4000,default='',null=True, blank=True)
	status = models.CharField(max_length=1,choices=STATUS)
	create_time = models.DateTimeField(auto_now_add=True)
	update_time = models.DateTimeField(auto_now=True)


	user = models.ForeignKey(
		User,
		models.SET_NULL,
		blank=True,
		null=True
	)
	tags = models.ManyToManyField(Tag)

	def __str__(self):
		return self.title

	class Meta:
		ordering = ['-update_time']

	def create_tags(self, tags):
		tags_str = tags.strip()
		tags_list = tags_str.split(' ')
		for tag_str in tags_list:
			tag,created = Tag.objects.get_or_create(tag=tag_str.lower())
			self.tags.add(tag)

	def get_tags(self):
		return self.tags.all()
		
	def get_tags_str(self):
		tags = ''
		if self.get_tags:
			for tag in self.get_tags():
				tags = '{0} {1}'.format(tags, tag.tag)
			tags = tags.strip()
		return tags
	def get_comments(self):
		return Comment.objects.filter(article=self)



class Comment(models.Model):
	content = models.TextField(max_length=500)
	create_time = models.DateTimeField(auto_now_add=True)
	user = models.ForeignKey(User,models.SET_NULL,blank=True,null=True)
	article = models.ForeignKey(Article,models.SET_NULL,blank=True,null=True)

	class Meta:
		ordering = ['-create_time']

	def __str__(self):
		return self.content




class MyUser(User):
	class Meta:
		proxy = True

	def get_articles(self):
		return Article.objects.filter(user=self)
	def get_comments(self):
		return Comment.objects.filter(user=self)

blog/views.py
from django.shortcuts import redirect, render
from django.urls import reverse
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.views.decorators.csrf import requires_csrf_token
from django.conf import settings
from django.db.models import Count


import datetime
import uuid
import os

from form import ArticleForm,CommentForm
from models import Article,Tag,Comment,MyUser

# Create your views here.
def home(request):
	articles = Article.objects.filter(status=Article.PUBLISHED)
	title = 'Home'

	return base(request,articles,title)

def base(request,articles_list,title):
	paginator = Paginator(articles_list, 10) # Show 25 contacts per page

	page = request.GET.get('page')
	try:
		articles = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		articles = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		articles = paginator.page(paginator.num_pages)
	tags = Tag.objects.all()
	return render(request, 'blog/home.html',{'articles':articles,'title':title,'tags':tags})

def show(request,id):
	article = get_object_or_404(Article,id=id)
	title = 'Show'
	form = CommentForm(initial={'article_id':article.id})

	return render(request, 'blog/show.html',{'article':article,'title':title,'form':form})

def user(request,username):
	user = User.objects.filter(username=username)
	articles = Article.objects.filter(status=Article.PUBLISHED,user=user)
	title = username
	return base(request,articles,title)

def tag(request,tag):
	tags = Tag.objects.filter(tag=tag)
	articles = Article.objects.filter(status=Article.PUBLISHED,tags=tags)
	title = tag
	return base(request,articles,title)

def search(request):
	q = request.GET.get('q')
	articles = Article.objects.filter(status=Article.PUBLISHED,title__contains=q)
	title = 'Search'
	return base(request,articles,title)


def alltag(request):
	tags = Tag.objects.annotate(num_articles=Count('article')).order_by('-create_time').order_by('-num_articles')
	title = 'Alltag'
	return render(request, 'blog/alltag.html',{'tags':tags,'title':title})

def alluser(request):
	users = MyUser.objects.annotate(num_articles=Count('article'),num_comments=Count('comment')).order_by('-num_comments').order_by('-num_articles')
	title = 'Alluser'
	return render(request, 'blog/alluser.html',{'users':users,'title':title})

@login_required
def draft(request):
	articles = Article.objects.filter(status=Article.DRAFT,user=request.user)
	title = 'Draft'
	return base(request,articles,title)

@login_required
def upload(request):
	files = request.FILES['upload']
	date = datetime.datetime.now().strftime("%Y%m%d")
	name = '%s%s' % (uuid.uuid1(),'.png')
	
	dirpath = '%s/%s/' % (settings.UPLOAD_PATH,date)
	fullname = '%s/%s' % (dirpath,name)
	fullurl = '/%s/%s/%s' % (settings.UPLOAD_URL,date,name)

	if not os.path.exists(dirpath):
		os.makedirs(dirpath)

	with open(fullname, 'wb+') as destination:
		for chunk in files.chunks():
			destination.write(chunk)

	return HttpResponse(fullurl)

@login_required
def comment(request):
	form = CommentForm(request.POST)

	if form.is_valid():
		comment = Comment()
		comment.content = form.cleaned_data.get('content')
		comment.user = request.user
		id=form.cleaned_data.get('article_id')
		try:
			article = Article.objects.get(id=id)
			comment.article = article
			comment.save()
			article.save()
			rtn = {'status':True,'redirect':reverse('blog:show', args=[id])}
		except Article.DoesNotExist:
			rtn = {'status':False,'error':'Article is not exist'}
	else:
		rtn = {'status':False,'error':form.errors}

	return JsonResponse(rtn)

@login_required
def write(request):
	if request.method == 'POST':
		form = ArticleForm(request.POST)
		if form.is_valid():
			id = form.cleaned_data.get('id')
			try:
				article = Article.objects.get(id=id)
			except Article.DoesNotExist:
				article = Article()
			article.user = request.user
			article.title = form.cleaned_data.get('title')
			article.content = form.cleaned_data.get('content')
			article.status = form.cleaned_data.get('status')
			article.markdown = form.cleaned_data.get('markdown')
			article.save()
			tags = form.cleaned_data.get('tags')
			article.create_tags(tags)
			return redirect(reverse('blog:home'))
		else:
			return HttpResponse(form.errors.as_json());
			
	elif request.GET.get('id'):
		id = request.GET.get('id')
		article = Article.objects.get(id=id)
		tags = article.get_tags_str()
		form = ArticleForm(instance=article,initial={'tags': tags})

	else:
		form = ArticleForm()
	
	return render(request, 'blog/write.html', {'form':form})

blog/templates/blog/alltag.html
{% extends 'base.html' %}
{% block title %}
{{ title }}
{% endblock title %}

{% block main %}
<div class="row">
	<div class="col-md-10">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">{{ title }}</h3>
			</div>
			<div class="panel-body">
				<section class="articles">
					{% for tag in tags %}
						<article style="margin: 0 0 10px 0;border-bottom:1px solid #e3e3e3;padding:10px 0;">
							<div class="info">
								<span style="margin-right:10px;width:100px;display:inline-block;">
									<span class="glyphicon glyphicon-tag"></span>
									<a href="{% url 'blog:tag' tag %}">{{ tag }}</a>
								</span>
								<span style="margin-right:10px;width:200px;display:inline-block;">
									<span class="glyphicon glyphicon-calendar"></span>
									{{ tag.create_time }}
								</span>
								<span class="comments" style="width:100px;display:inline-block;">
							    	<span class="glyphicon glyphicon-book"></span>
							      		{{ tag.get_articles.count }} Articles
							    </span>

							    
									
							</div>
														  
						</article>
					{% endfor %}
				</section>



			</div>
		</div>
	</div>


</div>



{% endblock main %}

blog/templates/blog/alluser.html
{% extends 'base.html' %}
{% block title %}
{{ title }}
{% endblock title %}

{% block main %}
<div class="row">
	<div class="col-md-10">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">{{ title }}</h3>
			</div>
			<div class="panel-body">
				<section class="articles">
					{% for user in users %}
						<article style="margin: 0 0 10px 0;border-bottom:1px solid #e3e3e3;padding:10px 0;">
							<div class="info">
								<span style="margin-right:10px;width:100px;display:inline-block;">
									<span class="glyphicon glyphicon-user"></span>
									<a href="{% url 'blog:user' user.username %}">{{ user.username }}</a>
								</span>
								<span style="margin-right:10px;width:200px;display:inline-block;">
									<span class="glyphicon glyphicon-calendar"></span>
									{{ user.last_login }}
								</span>
								<span class="comments" style="width:100px;display:inline-block;">
							    	<span class="glyphicon glyphicon-book"></span>
							      		{{ user.get_articles.count }} Articles
							    </span>
								
								<span class="comments" style="width:100px;display:inline-block;">
							    	<span class="glyphicon glyphicon-comment"></span>
							      		{{ user.get_comments.count }} Comments
							    </span>
							    
									
							</div>
														  
						</article>
					{% endfor %}
				</section>



			</div>
		</div>
	</div>


</div>



{% endblock main %}

blog/templates/blog/article.html
<article style="margin: 0 0 10px 0">
	<h3 style="margin-top:0px;margin-bottom:5px">
		<a href="{% url 'blog:show' article.id %}">{{ article.title }}</a>
	</h3>
	<div class="info">
		<span style="margin-right:10px;">
			<span class="glyphicon glyphicon-calendar"></span>
			{{ article.update_time }}
		</span>
		<span style="margin-right:10px;">
			<span class="glyphicon glyphicon-user"></span>
			<a href="{% url 'blog:user' article.user %}">{{ article.user }}</a>
		</span>
		<span class="comments">
	    <span class="glyphicon glyphicon-comment"></span>
	      	{{ article.get_comments.count }} Comments
	    </span>
			
	</div>
	{% if article.get_tags %}
		<div class="info">
			<span >
				{% for tag in article.get_tags %}
					<a href="{% url 'blog:tag' tag %}" class="label label-default"  >{{ tag }}</a>
				{% endfor %}
			</span>
		</div>
	{% endif %}
	
	  
</article>

blog/templates/blog/home.html
{% extends 'base.html' %}
{% block title %}
{{ title }}
{% endblock title %}

{% block main %}
<div class="row">
	<div class="col-md-10">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">{{ title }}</h3>
			</div>
			<div class="panel-body">
				<section class="articles">
					{% for article in articles %}
						{% include 'blog/article.html' with article=article %}
					{% endfor %}
				</section>


				<ul class="pagination">
					{% if articles.has_previous %}
						<li><a href="?page={{ articles.previous_page_number }}">&laquo;</a></li>
					{% else %}
						<li class="disabled"><span>&laquo;</span></li>
					{% endif %}
					{% for i in articles.paginator.page_range %}
						{% if articles.number|add:10 > i and articles.number|add:-10 < i %}
							{% if articles.number == i %}
							  <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
							{% else %}
							  <li><a href="?page={{ i }}">{{ i }}</a></li>
							{% endif %}
						{% endif %}
					
				  	{% endfor %}
					{% if articles.has_next %}
						<li><a href="?page={{ articles.next_page_number }}">&raquo;</a></li>
					{% else %}
						<li class="disabled"><span>&raquo;</span></li>
					{% endif %}
				</ul>
			</div>
		</div>
	</div>

	<div class="col-md-2">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Tags</h3>
			</div>
			<div class="panel-body">
				{% for tag in tags %}
					<a href="{% url 'blog:tag' tag %}"><span class="label label-default" style="line-height:2.4">{{ tag }}</span></a>
				{% endfor %}
			</div>
		</div>
 
	</div>
</div>



{% endblock main %}

blog/templates/blog/show.html
{% extends 'base.html' %}
{% block title %}
Show
{% endblock title %}

{% load static %}
{% block head %}
  	<script src="{% static 'js/comment.js' %}"></script>
{% endblock head %}

{% block main %}

	<div class="panel panel-default panel-feed">

		<div class="panel-body">
			<section class="articles">
				{% if user and article.user == user %}
					<a href="{% url 'blog:write' %}?id={{ article.id }}" class="btn btn-primary pull-right " >Edit</a>
				{% endif %}
				
				{% include 'blog/article.html' with article=article %}
				<p>
					{{ article.content|safe }}
				</p>
			</section>

			<form action="{% url 'blog:comment' %}" method="post" role="form" id="comment" style="border-top: 1px solid #e3e3e3;">
			  {% csrf_token %}
			  {% for field in form.visible_fields %}
				<div class="form-group{% if field.errors %} has-error{% endif %}">
					<label for="{{ field.label }}">{{ field.label }}</label>
					{{ field }}
					{% if field.help_text %}
						<span class="help-block">{{ field.help_text|safe }}</span>
					{% endif %}
					{% for error in field.errors %}
						<label class="control-label">{{ error }}</label>
					{% endfor %}
				</div>
				{% endfor %}
				{% for field in form.hidden_fields %}
					{{ field }}
				{% endfor %}
			  <button type="submit" class="btn btn-primary btn-sm">Submit</button>
			</form>

			<div style="margin:10px 0;" >
				{% if article.get_comments.count > 0 %}
					<div class="comment" >
					{% for comment in article.get_comments %}
						  <div class="comment-text" style="border-top:1px solid #e3e3e3">
						    <h5>
						    	
								<span style="margin-right:10px;">
									<span class="glyphicon glyphicon-user"></span>
									<a href="{% url 'blog:user' comment.user %}">{{ comment.user }}</a>
								</span>
								<span style="margin-right:10px;">
									<span class="glyphicon glyphicon-calendar"></span>
									{{ comment.create_time }}
								</span>
						    </h5>
						    <p>{{ comment.content }}</p>
						  </div>
					{% endfor %}
					</div>
				{% else %}
					<div >Be the first one to comment</div>
				{% endif %}
			
			</div>
			
		</div>
	</div>

{% endblock main %}

blog/templates/blog/write.html
{% extends 'base.html' %}
{% block title %}
Write
{% endblock title %}

{% load static %}
{% block head %}
  	<script src="{% static 'js/marked.min.js' %}"></script>
  	<script src="{% static 'js/write.js' %}?v=16"></script>
{% endblock head %}

{% block main %}

	<div class="panel panel-default panel-feed">
		<div class="panel-heading">
			<h3 class="panel-title">Write</h3>
		</div>
		<div class="panel-body">
			<form action="{% url 'blog:write' %}" method="post" role="form">
			  {% csrf_token %}
			  {% for field in form.visible_fields %}
				<div class="form-group{% if field.errors %} has-error{% endif %}">
					<label for="{{ field.label }}">{{ field.label }}</label>
					{{ field }}
					{% if field.help_text %}
						<span class="help-block">{{ field.help_text|safe }}</span>
					{% endif %}
					{% for error in field.errors %}
						<label class="control-label">{{ error }}</label>
					{% endfor %}
				</div>
				{% endfor %}
				{% for field in form.hidden_fields %}
					{{ field }}
				{% endfor %}
				<div class="form-group">
					<label for="Preview">Preview</label>
					<div class="form-control"  id="preview" style="width: 100%;height: 100%;top: 0;left: 100%;z-index: 9999;overflow: auto;"></div>
				</div>
				<div id="upload" url="{% url 'blog:upload' %}">
				</div>


			  <button type="submit" class="btn btn-primary btn-sm">Save</button>
			</form>
		</div>
	</div>
	
{% endblock main %}