blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^home/',
        views.home,
        name='home'),
    url(r'^draft/',
        views.draft,
        name='draft'),
   	url(r'^user/(?P<username>\w+)/$',
        views.user,
        name='user'),
   	url(r'^tag/(?P<tag>\w+)/$',
        views.tag,
        name='tag'),
    url(r'^alluser/', views.alluser, name='alluser'),
    url(r'^alltag/', views.alltag, name='alltag'),
    url(r'^write/', views.write, name='write'),
    url(r'^search/', views.search, name='search'),
    url(r'^upload/', views.upload, name='upload'),
    url(r'^comment/', views.comment, name='comment'),
    url(r'^show/(?P<id>\d+)/$', views.show, name='show'),
]

mysite/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='blog:home', permanent=True),name='home'),
    url(r'^blog/', include('blog.urls')),
	url(r'^registration/', include('registration.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    
]

registration/urls.py
from django.conf.urls import url

from . import views

app_name = 'registration'
urlpatterns = [
    url(r'^login/',
        views.login,
        name='login'),
    url(r'^register/',
        views.register,
        name='register'),
   	url(r'^logout/',
        views.logout,
        name='logout'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}Title{% endblock %}</title>
	<link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
	
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>

	{% block head %}{% endblock %}
  </head>
  <body>
	  <header>
		<nav class="navbar navbar-default" role="navigation">
		  <div class="container">
			<div class="navbar-header">
			  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			  </button>
			  <a class="navbar-brand" href="{% url 'blog:home' %}">Blog</a>
			</div>
			<div class="collapse navbar-collapse" id="menu">
			  <ul class="nav navbar-nav">

				<li><a href="{% url 'blog:home' %}">Article</a></li>
				<li><a href="{% url 'blog:alluser' %}">User</a></li>
				<li><a href="{% url 'blog:alltag' %}">Tag</a></li>

			  </ul>
				<form class="navbar-form navbar-left" role="search" action="{% url 'blog:search' %}">
				  <div class="input-group" style="width:100%">
					<input type="text" class="form-control" name="q" placeholder="Search">
					<span class="input-group-btn">
					  <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
					</span>
				  </div>
				</form>

				

			  <ul class="nav navbar-nav navbar-right">
			  {% if user.is_authenticated %}
				
				  <li>
					<a href="{% url 'blog:user' user.username %}">{{ user.username }}</a>
				  </li>
				  <li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"><b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><a href="{% url 'blog:write' %}" >Write</a></li>
						<li><a href="{% url 'blog:draft' %}" >Draft</a></li>
					  	<li><a href="{% url 'registration:logout' %}">Logout</a></li>
					</ul>
				  </li>
				
			  {% else %}
				
				  <li>
					<a href="{% url 'registration:login' %}">Login</a>
				  </li>
				  <li>
					<a href="{% url 'registration:register' %}">Register</a>
				  </li>
				  
				
			  {% endif %}
			  </ul>

			</div>
		  </div>
		</nav>
	  </header>
	  <main>
		<div class="container">
		  {% block main %}
		  {% endblock main %}
		</div>
	  </main>
  </body>
</html>